name: Run tests

on:
    workflow_call:
        inputs:
            tags:
                required: true
                type: string
            environment:
                required: true
                type: string
            stage:
                required: true
                type: string

env:
    REGISTRY: ghcr.io

jobs:
    frontend-build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN}}

            - name: Docker build and push
              uses: docker/build-push-action@v5
              with:
                  context: frontend
                  target: ${{ inputs.stage }}
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/breizh-sport-frontend:${{ inputs.tags }}

    core-build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        permissions:
            contents: read
            packages: write
        defaults:
            run:
                working-directory: backend/core

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN}}

            - name: Docker build and push
              uses: docker/build-push-action@v5
              with:
                  context: frontend
                  target: ${{ inputs.stage }}
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/breizh-sport-core:${{ inputs.tags }}

    promotions-build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        permissions:
            contents: read
            packages: write
        defaults:
            run:
                working-directory: backend/promotions
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN}}

            - name: Docker build and push
              uses: docker/build-push-action@v5
              with:
                  context: frontend
                  target: ${{ inputs.stage }}
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/breizh-sport-promotions:${{ inputs.tags }}

    auth-build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        permissions:
            contents: read
            packages: write
        defaults:
            run:
                working-directory: backend/auth
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN}}

            - name: Docker build and push
              uses: docker/build-push-action@v5
              with:
                  context: frontend
                  target: ${{ inputs.stage }}
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/breizh-sport-auth:${{ inputs.tags }}

    profiles-build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        permissions:
            contents: read
            packages: write
        defaults:
            run:
                working-directory: backend/profiles
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN}}

            - name: Docker build and push
              uses: docker/build-push-action@v5
              with:
                  context: frontend
                  target: ${{ inputs.stage }}
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/breizh-sport-profiles:${{ inputs.tags }}

    contact-build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        permissions:
            contents: read
            packages: write
        defaults:
            run:
                working-directory: backend/contact
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN}}

            - name: Docker build and push
              uses: docker/build-push-action@v5
              with:
                  context: frontend
                  target: ${{ inputs.stage }}
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/breizh-sport-contact:${{ inputs.tags }}
