name: Run tests

on:
    push:

jobs:
    frontend-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    core-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend/core
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    promotions-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend/promotions
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    auth-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend/auth
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    profiles-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend/profiles
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    contact-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend/contact
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm ci

            - name: Run tests
              run: npm test
