name: Run deployment on development environment

on:
    push:
        branches: ["develop"]

jobs:
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit

    build:
        needs: [test]
        uses: ./.github/workflows/build.yml
        with:
            tags: dev
            environment: development
            registry_token: ${{ secrets.GITHUB_TOKEN }}
        secrets: inherit
