name: Deploy on Production Environment

on:
    push:
        branches: ["main"]

jobs:
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit

    build:
        needs: [test]
        uses: ./.github/workflows/build.yml
        with:
            tags: ${{ github.ref }}
            environment: production
            registry_token: ${{ secrets.GITHUB_TOKEN }}
        secrets: inherit
