name: Run deployment on staging environment

on:
    push:
        branches: ["releases/*"]

jobs:
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit

    build:
        needs: [test]
        uses: ./.github/workflows/build.yml
        with:
            tags: ${{ github.ref }}-staging
            environment: staging
        secrets: inherit
